[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vowed = "88wHexJKLPw8TSKPq1X61Kkvt9wxwB9uDegktYG2Q4Z3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
